//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddInformation
    {
        public int IdAddInform { get; set; }
        public int WorkerID { get; set; }
        public string Conscripted { get; set; }
        public string PcEducation { get; set; }
        public string DriverCategory { get; set; }
        public int Childrens { get; set; }
        public string FamilyStatus { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
