//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationWorker
    {
        public int IdEducationWorker { get; set; }
        public int WorkerID { get; set; }
        public int EducationID { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
