//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public int IdVacation { get; set; }
        public int WorkerID { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> AddTime { get; set; }
        public Nullable<int> QtyDay { get; set; }
        public int FootingID { get; set; }
    
        public virtual TypeFooting TypeFooting { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
