//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_WorkerBusinessTrip
    {
        public string ФИО_сторудника { get; set; }
        public System.DateTime Дата_начала_командировки { get; set; }
        public int Кол_во_дней { get; set; }
        public string Цель_поездки { get; set; }
    }
}
