//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_WorkerBusinessTrip
    {
        public string FIO { get; set; }
        public System.DateTime DateStartBus { get; set; }
        public Nullable<int> QtyDayBus { get; set; }
        public string PurposeOfTheTrip { get; set; }
        public string Photo { get; set; }
        public System.DateTime DateEnd { get; set; }
    }
}
