//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Post
    {
        public string FIO { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Post { get; set; }
        public decimal Salary { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> DateStartPost { get; set; }
        public Nullable<System.DateTime> DateEndPost { get; set; }
        public string Example { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public int Experience { get; set; }
        public System.DateTime Birthday { get; set; }
    }
}
