//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_WorkerVocation
    {
        public string FIO { get; set; }
        public System.DateTime DateStartVoc { get; set; }
        public Nullable<int> QtyDayVac { get; set; }
        public string Footing { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    }
}
